function [descriptor] = pb_descriptor_PreciseLocation()
%pb_descriptor_PreciseLocation Returns the descriptor for message PreciseLocation.
%   function [descriptor] = pb_descriptor_PreciseLocation()
%
%   See also pb_read_PreciseLocation
  
  descriptor = struct( ...
    'name', 'PreciseLocation', ...
    'full_name', 'PreciseLocation', ...
    'filename', 'protobuf_defs.proto', ...
    'containing_type', '', ...
    'fields', [ ...
      struct( ...
        'name', 'x', ...
        'full_name', 'PreciseLocation.x', ...
        'index', 1, ...
        'number', uint32(1), ...
        'type', uint32(2), ...
        'matlab_type', uint32(6), ...
        'wire_type', uint32(5), ...
        'label', uint32(1), ...
        'default_value', single(0), ...
        'read_function', @(x) typecast(x, 'single'), ...
        'write_function', @(x) typecast(single(x), 'uint8'), ...
        'options', struct('packed', false) ...
      ), ...
      struct( ...
        'name', 'y', ...
        'full_name', 'PreciseLocation.y', ...
        'index', 2, ...
        'number', uint32(2), ...
        'type', uint32(2), ...
        'matlab_type', uint32(6), ...
        'wire_type', uint32(5), ...
        'label', uint32(1), ...
        'default_value', single(0), ...
        'read_function', @(x) typecast(x, 'single'), ...
        'write_function', @(x) typecast(single(x), 'uint8'), ...
        'options', struct('packed', false) ...
      ) ...
    ], ...
    'extensions', [ ... % Not Implemented
    ], ...
    'nested_types', [ ... % Not implemented
    ], ...
    'enum_types', [ ... % Not Implemented
    ], ...
    'options', [ ... % Not Implemented
    ] ...
  );
  
  descriptor.field_indeces_by_number = java.util.HashMap;
  put(descriptor.field_indeces_by_number, uint32(1), 1);
  put(descriptor.field_indeces_by_number, uint32(2), 2);
  
