function [descriptor] = pb_descriptor_LabeledLocation()
%pb_descriptor_LabeledLocation Returns the descriptor for message LabeledLocation.
%   function [descriptor] = pb_descriptor_LabeledLocation()
%
%   See also pb_read_LabeledLocation
  
  descriptor = struct( ...
    'name', 'LabeledLocation', ...
    'full_name', 'LabeledLocation', ...
    'filename', 'protobuf_defs.proto', ...
    'containing_type', '', ...
    'fields', [ ...
      struct( ...
        'name', 'confidence', ...
        'full_name', 'LabeledLocation.confidence', ...
        'index', 1, ...
        'number', uint32(1), ...
        'type', uint32(2), ...
        'matlab_type', uint32(6), ...
        'wire_type', uint32(5), ...
        'label', uint32(1), ...
        'default_value', single(0), ...
        'read_function', @(x) typecast(x, 'single'), ...
        'write_function', @(x) typecast(single(x), 'uint8'), ...
        'options', struct('packed', false) ...
      ), ...
      struct( ...
        'name', 'lab', ...
        'full_name', 'LabeledLocation.lab', ...
        'index', 2, ...
        'number', uint32(2), ...
        'type', uint32(11), ...
        'matlab_type', uint32(9), ...
        'wire_type', uint32(2), ...
        'label', uint32(1), ...
        'default_value', struct([]), ...
        'read_function', @(x) pb_read_Label(x{1}, x{2}, x{3}), ...
        'write_function', @pblib_generic_serialize_to_string, ...
        'options', struct('packed', false) ...
      ), ...
      struct( ...
        'name', 'imgSub', ...
        'full_name', 'LabeledLocation.imgSub', ...
        'index', 3, ...
        'number', uint32(3), ...
        'type', uint32(11), ...
        'matlab_type', uint32(9), ...
        'wire_type', uint32(2), ...
        'label', uint32(1), ...
        'default_value', struct([]), ...
        'read_function', @(x) pb_read_ImageSubstrate(x{1}, x{2}, x{3}), ...
        'write_function', @pblib_generic_serialize_to_string, ...
        'options', struct('packed', false) ...
      ), ...
      struct( ...
        'name', 'vidSub', ...
        'full_name', 'LabeledLocation.vidSub', ...
        'index', 4, ...
        'number', uint32(4), ...
        'type', uint32(11), ...
        'matlab_type', uint32(9), ...
        'wire_type', uint32(2), ...
        'label', uint32(1), ...
        'default_value', struct([]), ...
        'read_function', @(x) pb_read_VideoSubstrate(x{1}, x{2}, x{3}), ...
        'write_function', @pblib_generic_serialize_to_string, ...
        'options', struct('packed', false) ...
      ), ...
      struct( ...
        'name', 'loc', ...
        'full_name', 'LabeledLocation.loc', ...
        'index', 5, ...
        'number', uint32(5), ...
        'type', uint32(11), ...
        'matlab_type', uint32(9), ...
        'wire_type', uint32(2), ...
        'label', uint32(1), ...
        'default_value', struct([]), ...
        'read_function', @(x) pb_read_BBox(x{1}, x{2}, x{3}), ...
        'write_function', @pblib_generic_serialize_to_string, ...
        'options', struct('packed', false) ...
      ), ...
      struct( ...
        'name', 'sloc', ...
        'full_name', 'LabeledLocation.sloc', ...
        'index', 6, ...
        'number', uint32(6), ...
        'type', uint32(11), ...
        'matlab_type', uint32(9), ...
        'wire_type', uint32(2), ...
        'label', uint32(1), ...
        'default_value', struct([]), ...
        'read_function', @(x) pb_read_Silhouette(x{1}, x{2}, x{3}), ...
        'write_function', @pblib_generic_serialize_to_string, ...
        'options', struct('packed', false) ...
      ) ...
    ], ...
    'extensions', [ ... % Not Implemented
    ], ...
    'nested_types', [ ... % Not implemented
    ], ...
    'enum_types', [ ... % Not Implemented
    ], ...
    'options', [ ... % Not Implemented
    ] ...
  );
  
  descriptor.field_indeces_by_number = java.util.HashMap;
  put(descriptor.field_indeces_by_number, uint32(1), 1);
  put(descriptor.field_indeces_by_number, uint32(2), 2);
  put(descriptor.field_indeces_by_number, uint32(3), 3);
  put(descriptor.field_indeces_by_number, uint32(4), 4);
  put(descriptor.field_indeces_by_number, uint32(5), 5);
  put(descriptor.field_indeces_by_number, uint32(6), 6);
  
