function [descriptor] = pb_descriptor_FramePathPair()
%pb_descriptor_FramePathPair Returns the descriptor for message FramePathPair.
%   function [descriptor] = pb_descriptor_FramePathPair()
%
%   See also pb_read_FramePathPair

  descriptor = struct( ...
    'name', 'FramePathPair', ...
    'full_name', 'FramePathPair', ...
    'filename', 'protobuf_defs.proto', ...
    'containing_type', '', ...
    'fields', [ ...
      struct( ...
        'name', 'frameNum', ...
        'full_name', 'FramePathPair.frameNum', ...
        'index', 1, ...
        'number', uint32(1), ...
        'type', uint32(3), ...
        'matlab_type', uint32(2), ...
        'wire_type', uint32(0), ...
        'label', uint32(1), ...
        'default_value', int64(0), ...
        'read_function', @(x) typecast(x, 'int64'), ...
        'write_function', @(x) typecast(int64(x), 'uint64'), ...
        'options', struct('packed', false) ...
      ), ...
      struct( ...
        'name', 'path', ...
        'full_name', 'FramePathPair.path', ...
        'index', 2, ...
        'number', uint32(2), ...
        'type', uint32(9), ...
        'matlab_type', uint32(7), ...
        'wire_type', uint32(2), ...
        'label', uint32(1), ...
        'default_value', '', ...
        'read_function', @(x) char(x{1}(x{2} : x{3})), ...
        'write_function', @uint8, ...
        'options', struct('packed', false) ...
      ) ...
    ], ...
    'extensions', [ ... % Not Implemented
    ], ...
    'nested_types', [ ... % Not implemented
    ], ...
    'enum_types', [ ... % Not Implemented
    ], ...
    'options', [ ... % Not Implemented
    ] ...
  );

  descriptor.field_indeces_by_number = java.util.HashMap;
  put(descriptor.field_indeces_by_number, uint32(1), 1);
  put(descriptor.field_indeces_by_number, uint32(2), 2);

